name: variscite_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.2.1+2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  variscite_dart:
    path: ../variscite_dart
  flutter_map: ^0.14.0
  dio: ^4.0.0
  geolocator: ^7.6.2
  cached_network_image: ^3.1.0
  geojson_vi: ^2.0.3
  color: ^3.0.0
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  # hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1
  flutter_form_builder: ^6.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
