name: variscite_mobile
description: Mobile client for Variscite API
publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  variscite_dart: ^0.1.4
  flutter_map: ^0.14.0
  geolocator: ^7.6.2
  cached_network_image: ^3.1.0
  geojson_vi: ^2.0.3
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  flutter_secure_storage: ^4.2.1
  flutter_form_builder: ^6.1.0+1
  oktoast: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
